server:
  port: 9090

spring:
  application:
    name: sentinel-server
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080

#      datasource:
#        dsl:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            #data-id: ${spring.application.name}-sentinel-flow
#            data-id: gzf-sentinel-flow
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sentinel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapper/*.xml



